name: Card Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Configure pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install -r cache/requirements.txt
      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: python main.py
      - name: Commit
        run: |-
          git add .
          git diff
          git config --global user.email "github-actions-bot@bleedmagic.github.io"
          git config --global user.name "Bleedmagic/CI-Bot"
          git commit -m "Update README.md and SVGs" -a || echo "No changes to commit"
          git push
