name: Pacman Game

on:
  schedule: # Executes every 24 hours
    - cron: '0 */24 * * *'

  workflow_dispatch: # Allows manual triggering

  push: # Runs on every push to the main branch
    branches:
      - main


jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Prepare pacman output (light and dark)
        run: |
          mkdir -p dist/pacman
          if [ -f pacman-contribution-graph.svg ]; then
            mv pacman-contribution-graph.svg dist/pacman/
          elif [ -f */pacman-contribution-graph.svg ]; then
            mv */pacman-contribution-graph.svg dist/pacman/
          fi

          if [ -f pacman-contribution-graph-dark.svg ]; then
            mv pacman-contribution-graph-dark.svg dist/pacman/
          elif [ -f */pacman-contribution-graph-dark.svg ]; then
            mv */pacman-contribution-graph-dark.svg dist/pacman/
          fi

      - name: Push pacman output to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
