name: Pacman Game

on:
  schedule: # Executes every 24 hours
    - cron: '0 */24 * * *'

  workflow_dispatch: # Allows manual triggering

  push: # Runs on every push to the main branch
    branches:
      - main


jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate pacman contribution graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          platform: github
          theme: dark
          speed: 1
          sound: false
          output: svg

      - name: Prepare pacman output (light and dark)
        run: |
          mkdir -p dist/pacman
          find . -path ./dist -prune -o -name 'pacman-contribution-graph.svg' -exec cp {} dist/pacman/ \;
          find . -path ./dist -prune -o -name 'pacman-contribution-graph-dark.svg' -exec cp {} dist/pacman/ \;

      - name: Push pacman output to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
